/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserTryOnRouteImport } from './routes/user.try-on'
import { Route as UserSalonsRouteImport } from './routes/user.salons'
import { Route as UserRecommendationRouteImport } from './routes/user.recommendation'
import { Route as UserProfileRouteImport } from './routes/user.profile'
import { Route as UserHomeRouteImport } from './routes/user.home'
import { Route as SalonBookingsRouteImport } from './routes/salon.bookings'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as UserBookingIdRouteImport } from './routes/user.booking.$id'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserTryOnRoute = UserTryOnRouteImport.update({
  id: '/try-on',
  path: '/try-on',
  getParentRoute: () => UserRoute,
} as any)
const UserSalonsRoute = UserSalonsRouteImport.update({
  id: '/salons',
  path: '/salons',
  getParentRoute: () => UserRoute,
} as any)
const UserRecommendationRoute = UserRecommendationRouteImport.update({
  id: '/recommendation',
  path: '/recommendation',
  getParentRoute: () => UserRoute,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)
const UserHomeRoute = UserHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => UserRoute,
} as any)
const SalonBookingsRoute = SalonBookingsRouteImport.update({
  id: '/salon/bookings',
  path: '/salon/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const UserBookingIdRoute = UserBookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => UserRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/user': typeof UserRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/salon/bookings': typeof SalonBookingsRoute
  '/user/home': typeof UserHomeRoute
  '/user/profile': typeof UserProfileRoute
  '/user/recommendation': typeof UserRecommendationRoute
  '/user/salons': typeof UserSalonsRoute
  '/user/try-on': typeof UserTryOnRoute
  '/user/booking/$id': typeof UserBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/user': typeof UserRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/salon/bookings': typeof SalonBookingsRoute
  '/user/home': typeof UserHomeRoute
  '/user/profile': typeof UserProfileRoute
  '/user/recommendation': typeof UserRecommendationRoute
  '/user/salons': typeof UserSalonsRoute
  '/user/try-on': typeof UserTryOnRoute
  '/user/booking/$id': typeof UserBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/user': typeof UserRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/salon/bookings': typeof SalonBookingsRoute
  '/user/home': typeof UserHomeRoute
  '/user/profile': typeof UserProfileRoute
  '/user/recommendation': typeof UserRecommendationRoute
  '/user/salons': typeof UserSalonsRoute
  '/user/try-on': typeof UserTryOnRoute
  '/user/booking/$id': typeof UserBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/user'
    | '/admin/approvals'
    | '/auth/login'
    | '/auth/register'
    | '/salon/bookings'
    | '/user/home'
    | '/user/profile'
    | '/user/recommendation'
    | '/user/salons'
    | '/user/try-on'
    | '/user/booking/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/user'
    | '/admin/approvals'
    | '/auth/login'
    | '/auth/register'
    | '/salon/bookings'
    | '/user/home'
    | '/user/profile'
    | '/user/recommendation'
    | '/user/salons'
    | '/user/try-on'
    | '/user/booking/$id'
  id:
    | '__root__'
    | '/'
    | '/user'
    | '/admin/approvals'
    | '/auth/login'
    | '/auth/register'
    | '/salon/bookings'
    | '/user/home'
    | '/user/profile'
    | '/user/recommendation'
    | '/user/salons'
    | '/user/try-on'
    | '/user/booking/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserRoute: typeof UserRouteWithChildren
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  SalonBookingsRoute: typeof SalonBookingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/try-on': {
      id: '/user/try-on'
      path: '/try-on'
      fullPath: '/user/try-on'
      preLoaderRoute: typeof UserTryOnRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/salons': {
      id: '/user/salons'
      path: '/salons'
      fullPath: '/user/salons'
      preLoaderRoute: typeof UserSalonsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/recommendation': {
      id: '/user/recommendation'
      path: '/recommendation'
      fullPath: '/user/recommendation'
      preLoaderRoute: typeof UserRecommendationRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/home': {
      id: '/user/home'
      path: '/home'
      fullPath: '/user/home'
      preLoaderRoute: typeof UserHomeRouteImport
      parentRoute: typeof UserRoute
    }
    '/salon/bookings': {
      id: '/salon/bookings'
      path: '/salon/bookings'
      fullPath: '/salon/bookings'
      preLoaderRoute: typeof SalonBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/booking/$id': {
      id: '/user/booking/$id'
      path: '/booking/$id'
      fullPath: '/user/booking/$id'
      preLoaderRoute: typeof UserBookingIdRouteImport
      parentRoute: typeof UserRoute
    }
  }
}

interface UserRouteChildren {
  UserHomeRoute: typeof UserHomeRoute
  UserProfileRoute: typeof UserProfileRoute
  UserRecommendationRoute: typeof UserRecommendationRoute
  UserSalonsRoute: typeof UserSalonsRoute
  UserTryOnRoute: typeof UserTryOnRoute
  UserBookingIdRoute: typeof UserBookingIdRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserHomeRoute: UserHomeRoute,
  UserProfileRoute: UserProfileRoute,
  UserRecommendationRoute: UserRecommendationRoute,
  UserSalonsRoute: UserSalonsRoute,
  UserTryOnRoute: UserTryOnRoute,
  UserBookingIdRoute: UserBookingIdRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserRoute: UserRouteWithChildren,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  SalonBookingsRoute: SalonBookingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
